"""add_editor_verification_and_setup_token

Revision ID: 2eb085e0963b
Revises: d98e91927745
Create Date: 2026-09-05 02:00:36.270639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb085e0963b'
down_revision: Union[str, Sequence[str], None] = 'd98e91927745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('setup_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('setup_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_setup_token'), 'users', ['setup_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_setup_token'), table_name='users')
    op.drop_column('users', 'setup_token_expires_at')
    op.drop_column('users', 'setup_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
